# Generated by Django 3.2.6 on 2021-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books_liczba_stron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='data_publikacji',
            field=models.CharField(max_length=30),
        ),
    ]
