# Generated by Django 3.2.6 on 2021-12-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_books_data_publikacji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='link_do_okladki',
            new_name='front_page_link',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='data_publikacji',
            new_name='isbn_nr',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='jezyk_publikacji',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='liczba_stron',
            new_name='page_count',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='numer_isbn',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='tytul',
            new_name='title',
        ),
    ]
