# Generated by Django 3.2.6 on 2021-12-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211202_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='isbn_nr',
            new_name='isbn',
        ),
    ]
